### ISSUE TITLE
Could not register mediator Error: self signed certificate

### ISSUE THREAD

**Issue by waayaa** [jembi/openhim-mediator-file-queue#34]
Hi,
New to openHIM. Any pointer on how to solve this will be appreciated.

 - error: Could not register mediator Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8)

**Comment by MattyJ007** [comment]
Hi waayaa,

Try adding this environment flag to your start command:
```
NODE_TLS_REJECT_UNAUTHORIZED=0
```
Your local OpenHIM is using self signed certificates over SSL therefore you need to bypass that error with this flag

**Comment by waayaa** [comment]
Thanks
