### ISSUE TITLE
Query strings need to be forwarded

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-mediator-file-queue#7]

**Comment by bausmeier** [comment]
As far as I can remember the paths are all set up in the config and don't forward any part of the original url.

**Comment by rcrichton** [comment]
Ok right, I'm needing to be able to pass through query strings. I'm not sure of a good way to do this as all the worker knows about is a file for the body. The file could be structured as json and include the original headers, url and body. But, I don't really want to make that big of a change.

**Comment by bausmeier** [comment]
Yeah that would also mean having to read the file into memory to read the different parts of the json. At the moment it just gets streamed directly to and from disk. This is only a problem for large files though and I think that the files currently being processed by the queue as we use it in production are quite small. Still, I think it would be best to store the metadata for a request separately from the body itself.

**Comment by rcrichton** [comment]
Perhaps a json file that has the same name as the body file with a `-metadata` suffix or something?

**Comment by bausmeier** [comment]
That's the sort of thing I had in mind.

**Comment by armageddon** [comment]
what about query string in the file name?

**Comment by armageddon** [comment]
unless the filename is significant
slightly uneasy about having 2 files
what if one goes missing? (it shouldn't but things happen:) )

**Comment by rcrichton** [comment]
@armageddon that would work I think. It may just get a bit ugly with special characters and long request params. Also, if we want to allow forwarding on metadata then we should probably support forwarding the headers to. I think a file would make more sense for this. We can always only enable metadata forwarding as an option on an endpoint config?

**Comment by armageddon** [comment]
the paradigm of the query strings kind of works I think, as the query strings are part of the url in the same way that they will be part of the filename

**Comment by armageddon** [comment]
yeah agree on the possible messiness of the filename.

**Comment by rcrichton** [comment]
I think the separate file makes sense, but only enable this on certain workers via a config option. This will keep the existing stuff working as it has been.

**Comment by armageddon** [comment]
and I like the idea of being able to forward other details about the request - so I guess a separate file would be good. I think we would need to mark the folder for the file somehow to flag that it contains metadata. Or perhaps every folder should contain a metadata folder that may or may not be populated....
I'm just worried that we get a folder with a file in it and we aren't sure if its supposed to have metadata or not. I think writing 2 files is different to writing 1 file ito complexity

**Comment by rcrichton** [comment]
Agreed, I can work on some way to mark a file so that we know whether it is supposed to have metadata or not.
